from functions.other_functions import get_time, get_token, add_log
from functions.client_functions import (get_tg_id,
                                        get_user_id,
                                        get_admins,
                                        get_profile_text,
                                        get_prev_orders,
                                        get_type_food_id,
                                        get_food_kb_info,
                                        get_food_text,
                                        set_order,
                                        get_count,
                                        clear_basket,
                                        set_rating,
                                        get_basket,
                                        get_text_basket,
                                        get_user_bonus,
                                        get_user_status,
                                        is_bonus_activated,
                                        update_user_bonus,
                                        get_current_discount,
                                        make_purchase,
                                        get_order_list_text,
                                        get_orders,
                                        cancel_order,
                                        get_order_info,
                                        get_order_status
                                        )
from functions.admin_functions import get_order_text
